language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vp-web' ]; then cd .. && eval "mv $currentfolder generator-vp-web" && cd generator-vp-web; fi

