# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "sass", "~> 3.3.2"
gem "compass", "~> 1.0.0.alpha.17"
gem "susy", "~> 2.1.1"
gem "sass-globbing", "~> 1.1.0"
gem "breakpoint", "~> 2.4.2"